FROM node:alpine as build

WORKDIR /client
COPY package.json . 
RUN npm i
COPY . .
RUN npm run build
CMD [ "npm", "run", "preview" ]
#FROM nginx
#COPY --from=build /client/dist /usr/share/nginx/html
#COPY nginx.conf /etc/nginx/conf.d/default.conf
